name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1 # must follow toolchain installation
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy -- --deny "warnings"
    - name: Build
      run: cargo build --verbose --features fail-on-warnings
    - name: Run tests
      run: cargo test --verbose --features fail-on-warnings
    - name: Build docs
      run: cargo doc --verbose --features fail-on-warnings
