name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build
      run: cargo build --verbose --features fail-on-warnings
    - name: Run tests
      run: cargo test --verbose --features fail-on-warnings
    - name: Build docs
      run: cargo doc --verbose --features fail-on-warnings
